site_name: OnlyDrops Guide

site_url: https://guide.onlydrops.in

repo_url: https://github.com/OnlyTools-Softwares/onlydrops-guide-docs
repo_name: OnlyDrops Guide

theme:
  name: shadcn

markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.blocks.details


extra:
  assets:
    exclude: |
      *.zip
      *.mov

extra_css:
  - stylesheets/extra.css