site_name: OnlyDrops Guide

site_url: https://guide.onlydrops.in

theme:
  name: shadcn
  show_title: true # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles 
        light: shadcn-light
        dark: github-dark
  show_datetime: false 
  icon: assets/logo.jpg

markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.blocks.details


extra:
  assets:
    exclude: |
      *.zip
      *.mov